// Generated by CoffeeScript 1.6.3
define(function(require) {
  var Resume, date, div, init, today, uxhr, _;
  _ = require('lodash');
  Resume = require('resume');
  uxhr = require('uxhr');
  div = document.getElementById('resume');
  date = new Date();
  today = "" + (date.getFullYear()) + "-" + (date.getMonth());
  uxhr('data/data.json', {}, {
    complete: function(res) {
      return init(JSON.parse(res));
    }
  });
  return init = function(data) {
    var resume;
    data = _.extend(data, {
      element: div
    });
    return resume = new Resume(data);
  };
});
