// Generated by CoffeeScript 1.6.3
define(function(require) {
  var util;
  return util = {
    strtotime: function(string) {
      return new Date("" + string + "-01T12:00:00");
    },
    log: function(message) {
      var time;
      time = +new Date();
      if (!this.time) {
        this.time = time;
      }
      console.log(message, " (" + (time - this.time) + "ms)");
      return this.time = time;
    },
    classList: {
      add: function(element, className) {
        if (element.tagName === 'circle') {
          return element.setAttribute('class', "" + className + " " + element.className.baseVal);
        } else {
          return element.className += " " + className;
        }
      },
      remove: function(element, className) {
        var regex;
        regex = new RegExp("(^|\\s)" + className + "(?:\\s|$)");
        if (element.tagName === 'circle') {
          return element.setAttribute('class', (element.className.baseVal + '').replace(regex, '$1'));
        } else {
          return element.className = (element.className + '').replace(regex, '$1');
        }
      },
      contains: function(element, className) {
        var value;
        value = element.className;
        if (element.tagName === 'circle') {
          value = value.baseVal;
        }
        return (value.indexOf(className)) > -1;
      }
    }
  };
});
